insert into 01u_0info_compay (`uid`,
`name`,
`buslicence`,
`orgcode`,
`legalname`,
`legalpersionid`,
`linkman`,
`linkmanmobile`,
`yewuyuan`,
`yewuid`,
`registration_place`,
`registration_money`,
`establishment_data`,
`main_business`
) select `uid`,
`name`,
`buslicence`,
`orgcode`,
`legalname`,
`legalpersionid`,
`linkman`,
`linkmanmobile`,
`yewuyuan`,
`yewuid`,
`registration_place`,
`registration_money`,
`establishment_data`,
`main_business`
 from wd.01u_0info_compay WHERE establishment_data >= curdate();