# 01u_0info
insert into 01u_0info (`uid`,
`time_h`,
`time_l`,
`uid_kefu`,
`kefu_settime`,
`uname`,
`personid`,
`card_type`,
`personfontimage`,
`personbackimage`,
`real_status`,
`real_status_time`,
`mobile`,
`mobile_status`,
`student_xxw_un`,
`student_status`,
`mobile_jiechu_time`,
`marriage`,
`education`,
`email`,
`email_status`,
`sex`,
`headpture`,
`tel`,
`phone`,
`qq`,
`wangwang`,
`birthday`,
`nation`,
`province`,
`city`,
`area`,
`v_area`,
`address`,
`kuaidi_address`,
`kuaidi_realname`,
`kuaidi_mobile`,
`question`,
`answer`,
`logintime`,
`ishave`,
`note`,
`contents`,
`addtime`,
`addip`,
`uptime`,
`upip`,
`lasttime`,
`lastip`,
`server_name`,
`ps`,
`status`,
`carcode`,
`yewuyuan`,
`yewuid`,
`jiankuanren_detail`,
`smscode`,
`smssendtime`,
`tjr`,
`way`,
`cjcs`,
`zgcs`,
`fway`,
`utype`,
`psid_address`,
`psid_fzjg`,
`psid_type`,
`psid_start`,
`psid_end`,
`real_status_note`,
`is_take_jx`,
`is_take_jx_2`,
`is_use_tyj`,
`sent_ancun`,
`save_ancun`
)
select
a.uid					         `uid`,
a.create_time	         `time_h`,
a.update_time	         `time_l`,
'0'				             `uid_kefu`,
'0000-00-00 00:00:00'  `kefu_settime`,
a.real_name						 `uname`,
a.card_id							 `personid`,
'0'										 `card_type`,
''										 `personfontimage`,
''										 `personbackimage`,
a.real_name_status		 `real_status`,
'0'										 `real_status_time`,
a.reg_mobile					 `mobile`,
'0'										 `mobile_status`,
''  									 `student_xxw_un`,
'0'										 `student_status`,
'0'										 `mobile_jiechu_time`,
'0'										 `marriage`,
''								     `education`,
a.email						     `email`,
a.email_status				 `email_status`,
b.sex									 `sex`,
b.avatar_pic_path			 `headpture`,
''										 `tel`,
''										 `phone`,
''									   `qq`,
''									   `wangwang`,
''										 `birthday`,
''									   `nation`,
''									   `province`,
''								     `city`,
'0'							       `area`,
''									   `v_area`,
''							       `address`,
'-'									   `kuaidi_address`,
'-'										 `kuaidi_realname`,
'-'										 `kuaidi_mobile`,
''									   `question`,
''								     `answer`,
'0'									   `logintime`,
'0'										 `ishave`,
''								     `note`,
''										 `contents`,
UNIX_TIMESTAMP(a.create_time)`addtime`,
b.add_ip							 `addip`,
UNIX_TIMESTAMP(a.create_time)`uptime`,
''									   `upip`,
'0'										 `lasttime`,
''										 `lastip`,
''										 `server_name`,
''										 `ps`,
'0'									   `status`,
''									   `carcode`,
''										 `yewuyuan`,
'0'										 `yewuid`,
''										 `jiankuanren_detail`,
'   '								   `smscode`,
'0000-00-00 00:00:00'	 `smssendtime`,
''									   `tjr`,
'1'									   `way`,
'0'										 `cjcs`,
'0'										 `zgcs`,
''									   `fway`,
a.user_type						 `utype`,
''							       `psid_address`,
''										 `psid_fzjg`,
'0'								  	 `psid_type`,
'0000-00-00'					 `psid_start`,
'0000-00-00'					 `psid_end`,
''							       `real_status_note`,
'0'							   	   `is_take_jx`,
'0'									   `is_take_jx_2`,
'0'								   	 `is_use_tyj`,
'0'							       `sent_ancun`,
''							       `save_ancun`
from rz_user.rz_user a
LEFT JOIN rz_user.rz_user_base_info b on a.uid = b.user_id
where a.create_time > DATE_FORMAT(DATE_SUB(curdate(),INTERVAL 1 DAY),"%Y-%m-%d 23:30:00")
and a.create_time <= DATE_FORMAT(curdate(),"%Y-%m-%d 23:30:00");