# 01u_0base
insert into 01u_0base (`uid`,
`time_h`,
`guid`,
`un`,
`uname`,
`bindname`,
`cid`,
`pass`,
`salt`,
`flag`,
`uc_id`,
`paypass`,
`old_pass`,
`old_encrystr_login`,
`is_old`,
`errmm_num`,
`errmm_last`,
`openid`,
`access_token`,
`expire_time`,
`utype`,
`isvaild`,
`validdate`
)
SELECT
uid										 `uid`,
create_time						 `time_h`,
""										 `guid`,
user_name						   `un`,
real_name						   `uname`,
""									   `bindname`,
"1"										 `cid`,
pwd										 `pass`,
salt									 `salt`,
'0'										 `flag`,
'0'									   `uc_id`,
pay_pwd							   `paypass`,
pwd								     `old_pass`,
''								     `old_encrystr_login`,
'0'								     `is_old`,
'0'										 `errmm_num`,
'0000-00-00'		 	     `errmm_last`,
''								     `openid`,
''										 `access_token`,
'0000-00-00 00:00:00'  `expire_time`,
user_type					     `utype`,
'0'								     `isvaild`,
'0000-00-00'					 `validdate`
from rz_user.rz_user
where create_time > DATE_FORMAT(DATE_SUB(curdate(),INTERVAL 1 DAY),"%Y-%m-%d 23:30:00")
and create_time <= DATE_FORMAT(curdate(),"%Y-%m-%d 23:30:00");