# 05b_1tenderfinal
insert into 05b_1tenderfinal
(     `id` ,
  `bid`,
  `uid` ,
  `status` ,
  `account`,
  `recover_account_all` ,
  `recover_account_interest` ,
  `recover_account_yes`,
  `recover_account_interest_yes` ,
  `recover_account_capital_yes`,
  `recover_account_sxf_yes`,
  `recover_account_wait` ,
  `recover_account_interest_wait` ,
  `recover_account_capital_wait` ,
  `recover_times`,
  `contents` ,
  `successtime`,
  `time_h` ,
  `per`,
  `pid` ,
  `cid` ,
  `at_1` ,
  `at_2`,
  `at_4` ,
  `at_5`,
  `orguid`,
  `sent_ancun`,
  `save_ancun`,
  `tid`,
  `lzid`,
  `aprplus`,
  `recover_account_interest_plus`,
  `recover_account_interest_plus_yes`,
  `hbid`,
  `jxid`,
  `htid`)
select
id																							`id` ,
borrow_id																				`bid`,
user_id																					`uid` ,
if(`status` in (0,1,2,3,4,5,6),'0','1')					`status` ,
real_amount																			`account`,
repayment_account														    `recover_account_all` ,
interest																				`recover_account_interest` ,
repayment_yes_amount														`recover_account_yes`,
repayment_yes_interest													`recover_account_interest_yes` ,
repayment_yes_amount-repayment_yes_interest			`recover_account_capital_yes`,
'0.00'																					`recover_account_sxf_yes`,
wait_amount+wait_interest												`recover_account_wait` ,
wait_interest																		`recover_account_interest_wait` ,
wait_amount																		  `recover_account_capital_wait` ,
'0'																							`recover_times`,
' '																							`contents` ,
create_time																			`successtime`,
create_time																			`time_h` ,
'1'																							`per`,
'0'																							`pid` ,
'0'																							`cid` ,
'-1.00'																					`at_1` ,
'-1.00'																					`at_2`,
'-1.00'																					`at_4` ,
'-1.00'																					`at_5`,
'0'																						  `orguid`,
'0'																							`sent_ancun`,
''																							`save_ancun`,
'0'																							`tid`,
'0'																						  `lzid`,
'0.00'																					`aprplus`,
'0.00'																					`recover_account_interest_plus`,
'0.00'																		  		`recover_account_interest_plus_yes`,
redpacket_id																		`hbid`,
coupon_id																				`jxid`,
detail_no																				`htid`
from rz_borrow.rz_borrow_tender
where create_time > DATE_FORMAT(DATE_SUB(curdate(),INTERVAL 2 DAY),"%Y-%m-%d 23:59:59") and create_time <= DATE_FORMAT(DATE_SUB(curdate(),INTERVAL 1 DAY),"%Y-%m-%d 23:59:59");