insert into 05b_1tenderdetail
(   `id`,
  `bid` ,
  `uid`,
  `status`,
  `account_tender` ,
  `account` ,
  `already_pay`,
  `bid_cur_money`,
  `is_auto` ,
  `addtime`,
  `addip`,
  `tender_auto_bianhao`,
  `successtime` ,
  `time_h`,
  `per` ,
  `pid`,
  `cid`,
  `ucid`,
  `zqzr`,
  `t_c_no`,
  `t_t_s`,
  `voteclt`,
  `lcid`,
  `at_1`,
  `at_2`,
  `at_4`,
  `at_5`,
  `hbid`,
  `aprplus`,
  `jxid`,
  `toubiao_time`)
select `id`,
  `bid` ,
  `uid`,
  `status`,
  `account_tender` ,
  `account` ,
  `already_pay`,
  `bid_cur_money`,
  `is_auto` ,
  `addtime`,
  `addip`,
  `tender_auto_bianhao`,
  `successtime` ,
  `time_h`,
  `per` ,
  `pid`,
  `cid`,
  `ucid`,
  `zqzr`,
  `t_c_no`,
  `t_t_s`,
  `voteclt`,
  `lcid`,
  `at_1`,
  `at_2`,
  `at_4`,
  `at_5`,
  `hbid`,
  `aprplus`,
  `jxid`,
  `toubiao_time`
from wd.05b_1tenderdetail
where time_h > DATE_FORMAT(DATE_SUB(curdate(),INTERVAL 1 DAY),"%Y-%m-%d 23:30:00") and time_h <= DATE_FORMAT(curdate(),"%Y-%m-%d 23:30:00");

