# 05b_2list_recover
insert into 05b_2list_recover
(
`cid`,
`status`,
`uid`,
`bid`,
`uid_borrower`,
`tender_id`,
`old_tenderid`,
`recover_status`,
`recover_period`,
`recover_time`,
`recover_times`,
`recover_yestime`,
`recover_yestimes`,
`recover_account`,
`recover_interest`,
`recover_capital`,
`recover_account_yes`,
`recover_interest_yes`,
`recover_capital_yes`,
`recover_sxf_yes`,
`recover_web`,
`recover_vouch`,
`late_days`,
`late_interest`,
`late_forfeit`,
`late_reminder`,
`is_benjin`,
`is_huankuan_auto`,
`tiqian_content`,
`note`,
`srcid`,
`time_h`,
`dianzi_status`,
`dianzi_time`,
`olduid`,
`trans`,
`lcid`,
`pid`,
`tgstatus`,
`tid`,
`aprplus`,
`recover_interest_plus`,
`recover_interest_plus_yes`
)
select
'0'																							`cid`,
status																					`status`,
user_id																					`uid`,
borrow_id																				`bid`,
'0'																						  `uid_borrower`,
tender_id																				`tender_id`,
'0'																						  `old_tenderid`,
status																					`recover_status`,
period																					`recover_period`,
date(repayment_time)														`recover_time`,
repayment_time																	`recover_times`,
date(repayment_yes_time)												`recover_yestime`,
repayment_yes_time															`recover_yestimes`,
repayment_amount																`recover_account`,
interest																		    `recover_interest`,
capital																				  `recover_capital`,
repayment_yes_amount														`recover_account_yes`,
repayment_yes_interest													`recover_interest_yes`,
repayment_yes_amount-repayment_yes_interest			`recover_capital_yes`,
manage_fee																		  `recover_sxf_yes`,
'0'																					    `recover_web`,
'0'																							`recover_vouch`,
'0'																							`late_days`,
'0.00'																					`late_interest`,
'0.00'																					`late_forfeit`,
'0.00'																					`late_reminder`,
'0'																					   	`is_benjin`,
'0'																						  `is_huankuan_auto`,
''																							`tiqian_content`,
''																							`note`,
'0'																							`srcid`,
create_time																			`time_h`,
'0' 																						`dianzi_status`,
'0000-00-00 00:00:00'														`dianzi_time`,
'0'																					    `olduid`,
'0'																							`trans`,
'0'																							`lcid`,
'0'																							`pid`,
'0'																							`tgstatus`,
'0'																							`tid`,
'0.00'																					`aprplus`,
'0.00'																					`recover_interest_plus`,
'0.00'																					`recover_interest_plus_yes`
from rz_borrow.rz_borrow_collection
where create_time > DATE_FORMAT(DATE_SUB(curdate(),INTERVAL 2 DAY),"%Y-%m-%d 23:59:59") and create_time <= DATE_FORMAT(DATE_SUB(curdate(),INTERVAL 1 DAY),"%Y-%m-%d 23:59:59");