insert into 05b_1tenderfinal
(     `id` ,
  `bid`,
  `uid` ,
  `status` ,
  `account`,
  `recover_account_all` ,
  `recover_account_interest` ,
  `recover_account_yes`,
  `recover_account_interest_yes` ,
  `recover_account_capital_yes`,
  `recover_account_sxf_yes`,
  `recover_account_wait` ,
  `recover_account_interest_wait` ,
  `recover_account_capital_wait` ,
  `recover_times`,
  `contents` ,
  `successtime`,
  `time_h` ,
  `per`,
  `pid` ,
  `cid` ,
  `at_1` ,
  `at_2`,
  `at_4` ,
  `at_5`,
  `orguid`,
  `sent_ancun`,
  `save_ancun`,
  `tid`,
  `lzid`,
  `aprplus`,
  `recover_account_interest_plus`,
  `recover_account_interest_plus_yes`,
  `hbid`,
  `jxid`,
  `htid`)
select   `id` ,
  `bid`,
  `uid` ,
  `status` ,
  `account`,
  `recover_account_all` ,
  `recover_account_interest` ,
  `recover_account_yes`,
  `recover_account_interest_yes` ,
  `recover_account_capital_yes`,
  `recover_account_sxf_yes`,
  `recover_account_wait` ,
  `recover_account_interest_wait` ,
  `recover_account_capital_wait` ,
  `recover_times`,
  `contents` ,
  `successtime`,
  `time_h` ,
  `per`,
  `pid` ,
  `cid` ,
  `at_1` ,
  `at_2`,
  `at_4` ,
  `at_5`,
  `orguid`,
  `sent_ancun`,
  `save_ancun`,
  `tid`,
  `lzid`,
  `aprplus`,
  `recover_account_interest_plus`,
  `recover_account_interest_plus_yes`,
  `hbid`,
  `jxid`,
  `htid`
from wd.05b_1tenderfinal
where time_h > DATE_FORMAT(DATE_SUB(curdate(),INTERVAL 1 DAY),"%Y-%m-%d 23:30:00") and time_h <= DATE_FORMAT(curdate(),"%Y-%m-%d 23:30:00");
