# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-21 03:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automatic', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'permissions': (('can_access_search_table_list', '可以访问数据查询功能页面'),), 'verbose_name_plural': '账户表'},
        ),
    ]
