# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-08 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automatic', '0002_menu_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='themes',
            field=models.CharField(choices=[('A类coffee色', 'type-a/theme-coffee.min.css')], default='A类coffee色', max_length=32, verbose_name='主题'),
        ),
    ]
