# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-21 06:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automatic', '0003_auto_20171221_1358'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'permissions': (('can_access_search_table_list', '可以访问数据查询功能页面'), ('can_change_avatar', '可以修改用户头像'), ('can_access_automatic_index', '可以访问自动化后台首页')), 'verbose_name_plural': '账户表'},
        ),
    ]
