# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-22 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automatic', '0004_auto_20180112_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sqlrecord',
            name='name',
            field=models.CharField(max_length=32, unique=True, verbose_name='sql名称'),
        ),
    ]
