# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-08 09:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('automatic', '0004_auto_20171208_1536'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(verbose_name='下载地址')),
                ('check_status', models.SmallIntegerField(choices=[(0, '未审核'), (1, '审核通过'), (2, '审核不通过')], default=0, verbose_name='审核状态')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('end_date', models.DateTimeField(default='2099-12-31 00:00:00', verbose_name='过期时间')),
            ],
        ),
        migrations.CreateModel(
            name='SQLFunc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='功能名称')),
            ],
        ),
        migrations.CreateModel(
            name='SQLRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='sql名称')),
                ('content', models.TextField(verbose_name='sql内容')),
                ('query_page', models.BooleanField(default=False, verbose_name='是否生成查询页面')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('func', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='automatic.SQLFunc', verbose_name='sql具备的功能')),
                ('roles', models.ManyToManyField(blank=True, default=None, to='automatic.Role', verbose_name='所属角色')),
            ],
        ),
        migrations.CreateModel(
            name='SQLTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='标签名称')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='themes',
            field=models.CharField(choices=[('type-a/theme-coffee.min.css', 'A类coffee色'), ('type-a/theme-dark.min.css', 'A类dark'), ('type-a/theme-dust.min.css', 'A类dust'), ('type-a/theme-light.min.css', 'A类light'), ('type-a/theme-lime.min.css', 'A类lime'), ('type-a/theme-mint.min.css', 'A类mint'), ('type-a/theme-navy.min.css', 'A类navy'), ('type-a/theme-ocean.min.css', 'A类ocean'), ('type-a/theme-prickly-pear.min.css', 'A类prickly-pear'), ('type-a/theme-purple.min.css', 'A类purple'), ('type-a/theme-well-red.min.css', 'A类well-red'), ('type-a/theme-yellow.min.css', 'A类yellow'), ('type-b/theme-coffee.min.css', 'B类coffee色'), ('type-b/theme-dark.min.css', 'B类dark'), ('type-b/theme-dust.min.css', 'B类dust'), ('type-b/theme-light.min.css', 'B类light'), ('type-b/theme-lime.min.css', 'B类lime'), ('type-b/theme-mint.min.css', 'B类mint'), ('type-b/theme-navy.min.css', 'B类navy'), ('type-b/theme-ocean.min.css', 'B类ocean'), ('type-b/theme-prickly-pear.min.css', 'B类prickly-pear'), ('type-b/theme-purple.min.css', 'B类purple'), ('type-b/theme-well-red.min.css', 'B类well-red'), ('type-b/theme-yellow.min.css', 'B类yellow'), ('type-c/theme-coffee.min.css', 'C类coffee色'), ('type-c/theme-dark.min.css', 'C类dark'), ('type-c/theme-dust.min.css', 'C类dust'), ('type-c/theme-light.min.css', 'C类light'), ('type-c/theme-lime.min.css', 'C类lime'), ('type-c/theme-mint.min.css', 'C类mint'), ('type-c/theme-navy.min.css', 'C类navy'), ('type-c/theme-ocean.min.css', 'C类ocean'), ('type-c/theme-prickly-pear.min.css', 'C类prickly-pear'), ('type-c/theme-purple.min.css', 'C类purple'), ('type-c/theme-well-red.min.css', 'C类well-red'), ('type-c/theme-yellow.min.css', 'C类yellow')], default='type-c/theme-dark.min.css', max_length=64, verbose_name='主题'),
        ),
        migrations.AddField(
            model_name='sqltag',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
        migrations.AddField(
            model_name='sqlrecord',
            name='tags',
            field=models.ManyToManyField(blank=True, default=None, to='automatic.SQLTag', verbose_name='标签'),
        ),
        migrations.AddField(
            model_name='sqlrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
        migrations.AddField(
            model_name='downloadrecord',
            name='check_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_check_download', to=settings.AUTH_USER_MODEL, verbose_name='审核用户'),
        ),
        migrations.AddField(
            model_name='downloadrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_download', to=settings.AUTH_USER_MODEL, verbose_name='下载用户'),
        ),
    ]
