# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-09 03:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('automatic', '0006_auto_20171208_2008'),
    ]

    operations = [
        migrations.RenameField(
            model_name='downloadrecord',
            old_name='url',
            new_name='download_url',
        ),
        migrations.AddField(
            model_name='downloadrecord',
            name='check_img',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='审核用图片'),
        ),
        migrations.AddField(
            model_name='downloadrecord',
            name='detail_url',
            field=models.TextField(default='', verbose_name='详细信息地址'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='downloadrecord',
            name='download_detail',
            field=models.CharField(default='', max_length=32, verbose_name='下载信息'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='downloadrecord',
            name='check_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_check_download', to=settings.AUTH_USER_MODEL, verbose_name='审核用户'),
        ),
    ]
