# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-09 03:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automatic', '0007_auto_20171209_1101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sqlrecord',
            name='func',
        ),
        migrations.AddField(
            model_name='sqlrecord',
            name='func',
            field=models.ManyToManyField(blank=True, to='automatic.SQLFunc', verbose_name='sql具备的功能'),
        ),
    ]
