# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-27 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automatic', '0008_role_download_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='check_download_status',
            field=models.BooleanField(default=False, verbose_name='是否可以审核下载记录'),
        ),
    ]
