# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-11 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automatic', '0009_auto_20171209_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadrecord',
            name='download_detail',
            field=models.CharField(max_length=264, verbose_name='下载信息'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='themes',
            field=models.CharField(choices=[('type-a/theme-coffee.min.css', 'A类coffee色'), ('type-a/theme-dark.min.css', 'A类dark'), ('type-a/theme-dust.min.css', 'A类dust'), ('type-a/theme-light.min.css', 'A类light'), ('type-a/theme-lime.min.css', 'A类lime'), ('type-a/theme-mint.min.css', 'A类mint'), ('type-a/theme-navy.min.css', 'A类navy'), ('type-a/theme-ocean.min.css', 'A类ocean'), ('type-a/theme-prickly-pear.min.css', 'A类prickly-pear'), ('type-a/theme-purple.min.css', 'A类purple'), ('type-a/theme-well-red.min.css', 'A类well-red'), ('type-a/theme-yellow.min.css', 'A类yellow'), ('type-b/theme-coffee.min.css', 'B类coffee色'), ('type-b/theme-dark.min.css', 'B类dark'), ('type-b/theme-dust.min.css', 'B类dust'), ('type-b/theme-light.min.css', 'B类light'), ('type-b/theme-lime.min.css', 'B类lime'), ('type-b/theme-mint.min.css', 'B类mint'), ('type-b/theme-navy.min.css', 'B类navy'), ('type-b/theme-ocean.min.css', 'B类ocean'), ('type-b/theme-prickly-pear.min.css', 'B类prickly-pear'), ('type-b/theme-purple.min.css', 'B类purple'), ('type-b/theme-well-red.min.css', 'B类well-red'), ('type-b/theme-yellow.min.css', 'B类yellow'), ('type-c/theme-coffee.min.css', 'C类coffee色'), ('type-c/theme-dark.min.css', 'C类dark'), ('type-c/theme-dust.min.css', 'C类dust'), ('type-c/theme-light.min.css', 'C类light'), ('type-c/theme-lime.min.css', 'C类lime'), ('type-c/theme-mint.min.css', 'C类mint'), ('type-c/theme-navy.min.css', 'C类navy'), ('type-c/theme-ocean.min.css', 'C类ocean'), ('type-c/theme-prickly-pear.min.css', 'C类prickly-pear'), ('type-c/theme-purple.min.css', 'C类purple'), ('type-c/theme-well-red.min.css', 'C类well-red'), ('type-c/theme-yellow.min.css', 'C类yellow')], default='type-c/theme-navy.min.css', max_length=64, verbose_name='主题'),
        ),
    ]
