# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-07 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automatic', '0009_role_check_download_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='sqlrecord',
            name='nick_name',
            field=models.CharField(max_length=32, null=True, unique=True, verbose_name='sql昵称'),
        ),
        migrations.AlterField(
            model_name='sqlrecord',
            name='usage',
            field=models.SmallIntegerField(choices=[(0, '生成查询页面'), (1, '首页展示'), (2, '日报数据提取'), (3, 'BI数据库辅助'), (4, '其他用途')], default=0, verbose_name='SQL记录用途'),
        ),
    ]
