# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-05 06:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automatic', '0021_sqlrecord_db_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sqlrecord',
            name='db_name',
            field=models.SmallIntegerField(choices=[(0, 'rz'), (1, 'rzjf'), (2, 'default')], default=0, verbose_name='对应库名'),
        ),
    ]
