# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-08 08:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automatic', '0022_auto_20180105_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='sqlrecord',
            name='directly_download_status',
            field=models.BooleanField(default=False, verbose_name='是否可以直接下载'),
        ),
    ]
