# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-11 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automatic', '0024_sqlrecord_list_per_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sqlrecord',
            name='list_per_page',
            field=models.SmallIntegerField(choices=[(10, '10'), (25, '25'), (50, '50'), (100, '100')], default='10', verbose_name='每页显示多少条'),
        ),
    ]
