# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-11 15:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('automatic', '0025_auto_20180111_1449'),
    ]

    operations = [
        migrations.CreateModel(
            name='SQLUsage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='SQL记录用途')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name_plural': 'SQL记录用途表',
            },
        ),
        migrations.AddField(
            model_name='sqlrecord',
            name='usage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='automatic.SQLUsage', verbose_name='SQL记录的用途'),
        ),
    ]
