# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-16 04:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qdate', models.DateField()),
                ('zhu_r', models.IntegerField()),
                ('sm_r', models.IntegerField()),
                ('sc_r', models.IntegerField()),
                ('xztz_r', models.IntegerField()),
                ('xztz_j', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cz_r', models.IntegerField()),
                ('cz_j', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tx_r', models.IntegerField()),
                ('tx_j', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tz_r', models.IntegerField()),
                ('tz_j', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tz_dl_r', models.IntegerField()),
                ('hk_r', models.IntegerField()),
                ('hk_j', models.DecimalField(decimal_places=2, max_digits=10)),
                ('zg_j', models.DecimalField(decimal_places=2, max_digits=10)),
                ('inflow', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
