# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-16 05:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseinfo',
            name='qdate',
            field=models.DateField(verbose_name='日期'),
        ),
    ]
