# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-22 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_auto_20170816_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseinfo',
            name='cz_j',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='充值金额'),
        ),
        migrations.AlterField(
            model_name='baseinfo',
            name='cz_r',
            field=models.IntegerField(verbose_name='充值人数'),
        ),
        migrations.AlterField(
            model_name='baseinfo',
            name='hk_j',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='回款金额'),
        ),
        migrations.AlterField(
            model_name='baseinfo',
            name='hk_r',
            field=models.IntegerField(verbose_name='回款人数'),
        ),
        migrations.AlterField(
            model_name='baseinfo',
            name='inflow',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='净流入'),
        ),
        migrations.AlterField(
            model_name='baseinfo',
            name='sc_r',
            field=models.IntegerField(verbose_name='首充人数'),
        ),
        migrations.AlterField(
            model_name='baseinfo',
            name='sm_r',
            field=models.IntegerField(verbose_name='实名人数'),
        ),
        migrations.AlterField(
            model_name='baseinfo',
            name='tx_j',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='提现金额'),
        ),
        migrations.AlterField(
            model_name='baseinfo',
            name='tx_r',
            field=models.IntegerField(verbose_name='提现人数'),
        ),
        migrations.AlterField(
            model_name='baseinfo',
            name='tz_dl_r',
            field=models.IntegerField(verbose_name='投资登录人数'),
        ),
        migrations.AlterField(
            model_name='baseinfo',
            name='tz_j',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='投资金额'),
        ),
        migrations.AlterField(
            model_name='baseinfo',
            name='tz_r',
            field=models.IntegerField(verbose_name='投资人数'),
        ),
        migrations.AlterField(
            model_name='baseinfo',
            name='xztz_j',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='新增投资金额'),
        ),
        migrations.AlterField(
            model_name='baseinfo',
            name='xztz_r',
            field=models.IntegerField(verbose_name='新增投资人数'),
        ),
        migrations.AlterField(
            model_name='baseinfo',
            name='zg_j',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='站岗金额'),
        ),
        migrations.AlterField(
            model_name='baseinfo',
            name='zhu_r',
            field=models.IntegerField(verbose_name='注册人数'),
        ),
    ]
