# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-22 09:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_auto_20170822_1658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseinfo',
            name='inflow',
        ),
        migrations.AddField(
            model_name='baseinfo',
            name='tz_b',
            field=models.IntegerField(null=True, verbose_name='投资笔数'),
        ),
    ]
