# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-23 03:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_auto_20170822_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseinfo',
            name='zg_r',
            field=models.IntegerField(null=True, verbose_name='站岗人数'),
        ),
    ]
