# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-24 02:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_baseinfo_zg_r'),
    ]

    operations = [
        migrations.CreateModel(
            name='QudaoName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sign', models.CharField(max_length=32, verbose_name='渠道标识')),
                ('name', models.CharField(max_length=32, verbose_name='渠道名称')),
            ],
        ),
    ]
