# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-24 02:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_qudaoname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qudaoname',
            name='name',
            field=models.CharField(db_index=True, max_length=32, verbose_name='渠道名称'),
        ),
        migrations.AlterField(
            model_name='qudaoname',
            name='sign',
            field=models.CharField(db_index=True, max_length=32, verbose_name='渠道标识'),
        ),
    ]
