# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-24 02:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_auto_20170824_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseinfo',
            name='qdate',
            field=models.DateField(db_index=True, verbose_name='日期'),
        ),
    ]
