# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-24 03:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_auto_20170824_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseinfo',
            name='tz_dl_r',
            field=models.IntegerField(null=True, verbose_name='投资登录人数'),
        ),
    ]
