# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-24 03:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_auto_20170824_1100'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qdate', models.DateField(db_index=True, verbose_name='日期')),
                ('term', models.CharField(max_length=32, verbose_name='期限类型')),
                ('tz_r', models.IntegerField(verbose_name='投资人数')),
                ('tz_j', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='投资金额')),
                ('mb_ys', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='满标用时')),
            ],
        ),
        migrations.CreateModel(
            name='InviteInof',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qdate', models.DateField(db_index=True, verbose_name='日期')),
                ('invite_r', models.IntegerField(verbose_name='邀请人数')),
                ('invited_r', models.IntegerField(verbose_name='被邀请人数')),
                ('invited_st_r', models.IntegerField(verbose_name='被邀请首投人数')),
                ('invited_st_j', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='被邀请首投金额')),
                ('cash_f', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='现金奖励发放金额')),
                ('cash_l', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='现金奖励领取金额')),
                ('hb_f', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='邀请红包发放金额')),
                ('hb_s', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='邀请红包使用金额')),
            ],
        ),
        migrations.CreateModel(
            name='KeFuInof',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qdate', models.DateField(db_index=True, verbose_name='日期')),
                ('st_ft_r', models.IntegerField(verbose_name='首投后复投人数')),
                ('st_r', models.IntegerField(verbose_name='首投人数')),
                ('ls_r', models.IntegerField(verbose_name='流失用户')),
                ('zt_r', models.IntegerField(verbose_name='在投用户')),
            ],
        ),
        migrations.CreateModel(
            name='OperateInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qdate', models.DateField(db_index=True, verbose_name='日期')),
                ('xz_cz', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='新增充值')),
                ('hk_cz', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='回款并充值')),
                ('unhk_cz', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='非回款充值')),
                ('zj_ft_lv', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='资金复投率')),
                ('rs_ft_lv', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='人数复投率')),
            ],
        ),
        migrations.CreateModel(
            name='TgInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qdate', models.DateField(db_index=True, verbose_name='日期')),
                ('tg_zhu_r', models.IntegerField(verbose_name='推广注册人数')),
                ('tg_sm_r', models.IntegerField(verbose_name='推广实名人数')),
                ('tg_sc_r', models.IntegerField(verbose_name='推广首充人数')),
                ('tg_xztz_r', models.IntegerField(verbose_name='推广新增人数')),
                ('tg_xztz_j', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='推广新增金额')),
            ],
        ),
    ]
