# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-24 06:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_auto_20170824_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operateinfo',
            name='rs_ft_lv',
            field=models.DecimalField(decimal_places=4, max_digits=10, verbose_name='人数复投率'),
        ),
        migrations.AlterField(
            model_name='operateinfo',
            name='zj_ft_lv',
            field=models.DecimalField(decimal_places=4, max_digits=10, verbose_name='资金复投率'),
        ),
    ]
