# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-29 02:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0013_wdzj_info'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WDZJ_Info',
        ),
    ]
