# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-29 03:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0015_wdzj_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='WDTY_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qdate', models.DateField(db_index=True, null=True, verbose_name='日期')),
                ('name', models.CharField(max_length=32, verbose_name='平台名称')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='平台成交额(万)')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='平台综合利率(%)')),
                ('pnum', models.IntegerField(verbose_name='平台投资人数(人)')),
                ('cycle', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='平台借款周期(月)')),
                ('p1num', models.IntegerField(verbose_name='平台借款人(人)')),
                ('fuload', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='平台满标速度(分钟)')),
                ('alltotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='平台累计贷款余额(万)')),
                ('capital', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='平台资金净流入(万)')),
            ],
        ),
    ]
