# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-29 08:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0016_wdty_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseinfo',
            name='zd_j',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='在贷金额'),
        ),
        migrations.AddField(
            model_name='baseinfo',
            name='zd_r',
            field=models.IntegerField(null=True, verbose_name='在贷人数'),
        ),
    ]
