# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-31 11:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0019_auto_20170831_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wdty_info',
            name='alltotal',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='平台累计贷款余额(万)'),
        ),
        migrations.AlterField(
            model_name='wdty_info',
            name='capital',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='平台资金净流入(万)'),
        ),
        migrations.AlterField(
            model_name='wdty_info',
            name='cycle',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='平台借款周期(月)'),
        ),
        migrations.AlterField(
            model_name='wdty_info',
            name='fuload',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='平台满标速度(分钟)'),
        ),
        migrations.AlterField(
            model_name='wdty_info',
            name='name',
            field=models.CharField(max_length=32, null=True, verbose_name='平台名称'),
        ),
        migrations.AlterField(
            model_name='wdty_info',
            name='p1num',
            field=models.IntegerField(null=True, verbose_name='平台借款人(人)'),
        ),
        migrations.AlterField(
            model_name='wdty_info',
            name='pnum',
            field=models.IntegerField(null=True, verbose_name='平台投资人数(人)'),
        ),
        migrations.AlterField(
            model_name='wdty_info',
            name='rate',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='平台综合利率(%)'),
        ),
        migrations.AlterField(
            model_name='wdty_info',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='平台成交额(万)'),
        ),
        migrations.AlterField(
            model_name='wdzj_info',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='成交量(万元)'),
        ),
        migrations.AlterField(
            model_name='wdzj_info',
            name='avgBidMoney',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='人均投资金额(万元)'),
        ),
        migrations.AlterField(
            model_name='wdzj_info',
            name='avgBorrowMoney',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='人均借款金额(万元)'),
        ),
        migrations.AlterField(
            model_name='wdzj_info',
            name='bidderNum',
            field=models.IntegerField(null=True, verbose_name='投资人数(人)'),
        ),
        migrations.AlterField(
            model_name='wdzj_info',
            name='borrowerNum',
            field=models.IntegerField(null=True, verbose_name='借款人数(人)'),
        ),
        migrations.AlterField(
            model_name='wdzj_info',
            name='developZhishu',
            field=models.IntegerField(null=True, verbose_name='发展指数排名'),
        ),
        migrations.AlterField(
            model_name='wdzj_info',
            name='fullloanTime',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='满标用时(分)'),
        ),
        migrations.AlterField(
            model_name='wdzj_info',
            name='incomeRate',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='平均预期收益率(%)'),
        ),
        migrations.AlterField(
            model_name='wdzj_info',
            name='loanPeriod',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='平均借款期限(月)'),
        ),
        migrations.AlterField(
            model_name='wdzj_info',
            name='netInflowOfThirty',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='资金净流入(万元)'),
        ),
        migrations.AlterField(
            model_name='wdzj_info',
            name='platName',
            field=models.CharField(max_length=32, null=True, verbose_name='平台名称'),
        ),
        migrations.AlterField(
            model_name='wdzj_info',
            name='regCapital',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='注册资本(万元)'),
        ),
        migrations.AlterField(
            model_name='wdzj_info',
            name='stayStillOfTotal',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='待还余额(万元)'),
        ),
        migrations.AlterField(
            model_name='wdzj_info',
            name='timeOperation',
            field=models.IntegerField(null=True, verbose_name='运营时间(月)'),
        ),
        migrations.AlterField(
            model_name='wdzj_info',
            name='top10DueInProportion',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='前十大土豪待收金额占比(%)'),
        ),
        migrations.AlterField(
            model_name='wdzj_info',
            name='top10StayStillProportion',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='前十大借款人待还金额占比(%)'),
        ),
        migrations.AlterField(
            model_name='wdzj_info',
            name='totalLoanNum',
            field=models.IntegerField(null=True, verbose_name='借款标数(个)'),
        ),
    ]
