# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-09-05 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0021_geduaninfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geduaninfo',
            name='account',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='各端投资'),
        ),
        migrations.AlterField(
            model_name='geduaninfo',
            name='recover',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='各端已还'),
        ),
        migrations.AlterField(
            model_name='geduaninfo',
            name='recover_withdraw',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='各端回款并提现'),
        ),
        migrations.AlterField(
            model_name='geduaninfo',
            name='withdraw',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='各端提现金额'),
        ),
        migrations.AlterField(
            model_name='geduaninfo',
            name='xztz_j',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='各端新增投资'),
        ),
    ]
