# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-09-11 16:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0026_user_update_time'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='rzjf_user',
        ),
    ]
