# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-09-11 16:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0027_auto_20170911_1616'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='assetinfo',
            table='rzjf_asset_info',
        ),
        migrations.AlterModelTable(
            name='baseinfo',
            table='rzjf_base_info',
        ),
        migrations.AlterModelTable(
            name='geduaninfo',
            table='rzjf_geduan_info',
        ),
        migrations.AlterModelTable(
            name='inviteinfo',
            table='rzjf_invite_info',
        ),
        migrations.AlterModelTable(
            name='kefuinfo',
            table='rzjf_kefu_info',
        ),
        migrations.AlterModelTable(
            name='operateinfo',
            table='rzjf_operate_info',
        ),
        migrations.AlterModelTable(
            name='qudaoname',
            table='rzjf_qudao_name',
        ),
        migrations.AlterModelTable(
            name='tginfo',
            table='rzjf_tg_info',
        ),
        migrations.AlterModelTable(
            name='wdty_info',
            table='rzjf_wdty_info',
        ),
        migrations.AlterModelTable(
            name='wdzj_info',
            table='rzjf_wdzj_info',
        ),
    ]
