# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-09-12 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0028_auto_20170911_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='tginfo',
            name='tg_cost',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='推广花费'),
        ),
    ]
