# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-09-13 10:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0029_tginfo_tg_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qdate', models.DateField(db_index=True, verbose_name='日期')),
                ('cz_fee', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='充值手续费')),
                ('short_tz_r', models.IntegerField(null=True, verbose_name='30天以内短标交易人数')),
                ('short_tz_j', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='30天以内短标交易金额')),
                ('short_zd_j', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='30天以内短标待还总额')),
            ],
            options={
                'verbose_name_plural': '其他数据',
                'verbose_name': '其他数据',
                'db_table': 'rzjf_other_info',
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qdate', models.DateField(db_index=True, verbose_name='日期')),
                ('timeslot', models.IntegerField(verbose_name='时间段')),
                ('tz_r', models.IntegerField(verbose_name='投资人数')),
            ],
            options={
                'verbose_name_plural': '各时间段数据',
                'verbose_name': '各时间段数据',
                'db_table': 'rzjf_time_slot',
            },
        ),
    ]
