# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-22 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0030_otherinfo_timeslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(null=True, upload_to='', verbose_name='头像'),
        ),
    ]
