# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-22 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0031_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(null=True, upload_to='img', verbose_name='头像'),
        ),
    ]
