# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-27 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0033_auto_20170922_1546'),
    ]

    operations = [
        migrations.CreateModel(
            name='TgQudaoName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='渠道名称')),
                ('sign', models.CharField(max_length=500, verbose_name='渠道标识')),
            ],
        ),
    ]
