# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-28 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0035_auto_20170927_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='otherinfo',
            name='Rplan_account',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='R计划投资金额'),
        ),
        migrations.AddField(
            model_name='otherinfo',
            name='Rplan_recover_account',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='R计划在贷金额'),
        ),
    ]
