# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-04 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0037_auto_20171004_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otherinfo',
            name='Rplan_account',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True, verbose_name='R计划投资金额'),
        ),
        migrations.AlterField(
            model_name='otherinfo',
            name='cz_fee',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True, verbose_name='充值手续费'),
        ),
        migrations.AlterField(
            model_name='otherinfo',
            name='short_tz_j',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True, verbose_name='30天以内短标交易金额'),
        ),
        migrations.AlterField(
            model_name='otherinfo',
            name='short_zd_j',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True, verbose_name='30天以内短标待还总额'),
        ),
    ]
