# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-10 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0038_auto_20171004_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otherinfo',
            name='cz_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='充值手续费'),
        ),
    ]
