# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-10 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0039_auto_20171010_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tginfo',
            name='tg_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='推广花费'),
        ),
    ]
