# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-11 11:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0040_auto_20171010_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='otherinfo',
            name='g_tz_j',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='供应链金融投资金额'),
        ),
        migrations.AddField(
            model_name='otherinfo',
            name='x_tz_j',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='消费金融投资金额'),
        ),
    ]
