# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-12 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0041_auto_20171011_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetinfo',
            name='asset_type',
            field=models.CharField(default='所有', max_length=32, verbose_name='资产类型'),
        ),
    ]
