# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-18 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0042_assetinfo_asset_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='otherinfo',
            name='Rplan_xt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='R计划续投金额'),
        ),
    ]
