# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-20 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0043_otherinfo_rplan_xt'),
    ]

    operations = [
        migrations.AddField(
            model_name='otherinfo',
            name='unRplan_xt_hk_j',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='非R计划自动续投金额'),
        ),
    ]
