# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-24 16:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0044_otherinfo_unrplan_xt_hk_j'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TgQudaoName',
        ),
    ]
