# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-02 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0046_dailyassetinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyassetinfo',
            name='mb_ys',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='满标用时'),
        ),
    ]
