# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-02 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0047_auto_20171102_1155'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyWithdrawClassify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qdate', models.DateField(db_index=True, verbose_name='日期')),
                ('term', models.CharField(max_length=32, verbose_name='提现分类')),
                ('tx_r', models.IntegerField(verbose_name='提现人数')),
                ('tx_j', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='提现金额')),
                ('asset_type', models.CharField(default='所有', max_length=32, verbose_name='提现类型')),
            ],
            options={
                'verbose_name': '日报提现分类数据',
                'verbose_name_plural': '日报提现分类数据',
                'db_table': 'rzjf_daily_withdraw_classify',
            },
        ),
    ]
