# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-02 14:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0048_dailywithdrawclassify'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailywithdrawclassify',
            old_name='asset_type',
            new_name='withdraw_type',
        ),
    ]
