# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-02 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0049_auto_20171102_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailywithdrawclassify',
            name='tx_j',
            field=models.DecimalField(decimal_places=2, max_digits=30, verbose_name='提现金额'),
        ),
    ]
