# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-02 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0050_auto_20171102_1441'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyCollectClassify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qdate', models.DateField(db_index=True, verbose_name='日期')),
                ('term', models.CharField(max_length=32, verbose_name='待收分类')),
                ('collect_r', models.IntegerField(verbose_name='待收人数')),
                ('collect_j', models.DecimalField(decimal_places=2, max_digits=30, verbose_name='待收金额')),
                ('collect_type', models.CharField(default='所有', max_length=32, verbose_name='待收类型')),
            ],
            options={
                'verbose_name': '日报待收分类数据',
                'verbose_name_plural': '日报待收分类数据',
                'db_table': 'rzjf_daily_collect_classify',
            },
        ),
    ]
