# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-08 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0051_dailycollectclassify'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inviteinfo',
            name='cash_l',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='现金奖励领取金额'),
        ),
        migrations.AlterField(
            model_name='inviteinfo',
            name='hb_f',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='邀请红包发放金额'),
        ),
        migrations.AlterField(
            model_name='inviteinfo',
            name='hb_s',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='邀请红包使用金额'),
        ),
    ]
