# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-09 10:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0052_auto_20171108_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetinfo',
            name='asset_type',
            field=models.CharField(default='所有', max_length=32, null=True, verbose_name='资产类型'),
        ),
        migrations.AlterField(
            model_name='assetinfo',
            name='mb_ys',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='满标用时'),
        ),
        migrations.AlterField(
            model_name='assetinfo',
            name='term',
            field=models.CharField(max_length=32, null=True, verbose_name='期限类型'),
        ),
        migrations.AlterField(
            model_name='assetinfo',
            name='tz_j',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='投资金额'),
        ),
        migrations.AlterField(
            model_name='assetinfo',
            name='tz_r',
            field=models.IntegerField(null=True, verbose_name='投资人数'),
        ),
        migrations.AlterField(
            model_name='baseinfo',
            name='cz_j',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='充值金额'),
        ),
        migrations.AlterField(
            model_name='baseinfo',
            name='cz_r',
            field=models.IntegerField(null=True, verbose_name='充值人数'),
        ),
        migrations.AlterField(
            model_name='baseinfo',
            name='hk_j',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='回款金额'),
        ),
        migrations.AlterField(
            model_name='baseinfo',
            name='hk_r',
            field=models.IntegerField(null=True, verbose_name='回款人数'),
        ),
        migrations.AlterField(
            model_name='baseinfo',
            name='sc_r',
            field=models.IntegerField(null=True, verbose_name='首充人数'),
        ),
        migrations.AlterField(
            model_name='baseinfo',
            name='sm_r',
            field=models.IntegerField(null=True, verbose_name='实名人数'),
        ),
        migrations.AlterField(
            model_name='baseinfo',
            name='tx_j',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='提现金额'),
        ),
        migrations.AlterField(
            model_name='baseinfo',
            name='tx_r',
            field=models.IntegerField(null=True, verbose_name='提现人数'),
        ),
        migrations.AlterField(
            model_name='baseinfo',
            name='tz_j',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='投资金额'),
        ),
        migrations.AlterField(
            model_name='baseinfo',
            name='tz_r',
            field=models.IntegerField(null=True, verbose_name='投资人数'),
        ),
        migrations.AlterField(
            model_name='baseinfo',
            name='xztz_j',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='新增投资金额'),
        ),
        migrations.AlterField(
            model_name='baseinfo',
            name='xztz_r',
            field=models.IntegerField(null=True, verbose_name='新增投资人数'),
        ),
        migrations.AlterField(
            model_name='baseinfo',
            name='zg_j',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='站岗金额'),
        ),
        migrations.AlterField(
            model_name='baseinfo',
            name='zhu_r',
            field=models.IntegerField(null=True, verbose_name='注册人数'),
        ),
        migrations.AlterField(
            model_name='dailyassetinfo',
            name='asset_type',
            field=models.CharField(default='所有', max_length=32, null=True, verbose_name='资产类型'),
        ),
        migrations.AlterField(
            model_name='dailyassetinfo',
            name='term',
            field=models.CharField(max_length=32, null=True, verbose_name='期限类型'),
        ),
        migrations.AlterField(
            model_name='dailyassetinfo',
            name='tz_j',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='投资金额'),
        ),
        migrations.AlterField(
            model_name='dailyassetinfo',
            name='tz_r',
            field=models.IntegerField(null=True, verbose_name='投资人数'),
        ),
        migrations.AlterField(
            model_name='dailycollectclassify',
            name='collect_j',
            field=models.DecimalField(decimal_places=2, max_digits=30, null=True, verbose_name='待收金额'),
        ),
        migrations.AlterField(
            model_name='dailycollectclassify',
            name='collect_r',
            field=models.IntegerField(null=True, verbose_name='待收人数'),
        ),
        migrations.AlterField(
            model_name='dailycollectclassify',
            name='collect_type',
            field=models.CharField(default='所有', max_length=32, null=True, verbose_name='待收类型'),
        ),
        migrations.AlterField(
            model_name='dailycollectclassify',
            name='term',
            field=models.CharField(max_length=32, null=True, verbose_name='待收分类'),
        ),
        migrations.AlterField(
            model_name='dailywithdrawclassify',
            name='term',
            field=models.CharField(max_length=32, null=True, verbose_name='提现分类'),
        ),
        migrations.AlterField(
            model_name='dailywithdrawclassify',
            name='tx_j',
            field=models.DecimalField(decimal_places=2, max_digits=30, null=True, verbose_name='提现金额'),
        ),
        migrations.AlterField(
            model_name='dailywithdrawclassify',
            name='tx_r',
            field=models.IntegerField(null=True, verbose_name='提现人数'),
        ),
        migrations.AlterField(
            model_name='dailywithdrawclassify',
            name='withdraw_type',
            field=models.CharField(default='所有', max_length=32, null=True, verbose_name='提现类型'),
        ),
        migrations.AlterField(
            model_name='geduaninfo',
            name='geduan',
            field=models.CharField(max_length=32, null=True, verbose_name='各端类型'),
        ),
        migrations.AlterField(
            model_name='inviteinfo',
            name='cash_f',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='现金奖励发放金额'),
        ),
        migrations.AlterField(
            model_name='inviteinfo',
            name='cash_l',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True, verbose_name='现金奖励领取金额'),
        ),
        migrations.AlterField(
            model_name='inviteinfo',
            name='hb_f',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True, verbose_name='邀请红包发放金额'),
        ),
        migrations.AlterField(
            model_name='inviteinfo',
            name='hb_s',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True, verbose_name='邀请红包使用金额'),
        ),
        migrations.AlterField(
            model_name='inviteinfo',
            name='invite_r',
            field=models.IntegerField(null=True, verbose_name='邀请人数'),
        ),
        migrations.AlterField(
            model_name='inviteinfo',
            name='invited_r',
            field=models.IntegerField(null=True, verbose_name='被邀请人数'),
        ),
        migrations.AlterField(
            model_name='inviteinfo',
            name='invited_st_j',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='被邀请首投金额'),
        ),
        migrations.AlterField(
            model_name='inviteinfo',
            name='invited_st_r',
            field=models.IntegerField(null=True, verbose_name='被邀请首投人数'),
        ),
        migrations.AlterField(
            model_name='kefuinfo',
            name='ls_r',
            field=models.IntegerField(null=True, verbose_name='流失用户'),
        ),
        migrations.AlterField(
            model_name='kefuinfo',
            name='st_ft_r',
            field=models.IntegerField(null=True, verbose_name='首投后复投人数'),
        ),
        migrations.AlterField(
            model_name='kefuinfo',
            name='st_r',
            field=models.IntegerField(null=True, verbose_name='首投人数'),
        ),
        migrations.AlterField(
            model_name='kefuinfo',
            name='zt_r',
            field=models.IntegerField(null=True, verbose_name='在投用户'),
        ),
        migrations.AlterField(
            model_name='operateinfo',
            name='hk_cz',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='回款并充值'),
        ),
        migrations.AlterField(
            model_name='operateinfo',
            name='rs_ft_lv',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True, verbose_name='人数复投率'),
        ),
        migrations.AlterField(
            model_name='operateinfo',
            name='unhk_cz',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='非回款充值'),
        ),
        migrations.AlterField(
            model_name='operateinfo',
            name='xz_cz',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='新增充值'),
        ),
        migrations.AlterField(
            model_name='operateinfo',
            name='zj_ft_lv',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True, verbose_name='资金复投率'),
        ),
        migrations.AlterField(
            model_name='otherinfo',
            name='Rplan_xt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, null=True, verbose_name='R计划续投金额'),
        ),
        migrations.AlterField(
            model_name='otherinfo',
            name='g_tz_j',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, null=True, verbose_name='供应链金融投资金额'),
        ),
        migrations.AlterField(
            model_name='otherinfo',
            name='unRplan_xt_hk_j',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, null=True, verbose_name='非R计划自动续投金额'),
        ),
        migrations.AlterField(
            model_name='otherinfo',
            name='x_tz_j',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, null=True, verbose_name='消费金融投资金额'),
        ),
        migrations.AlterField(
            model_name='tginfo',
            name='tg_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True, verbose_name='推广花费'),
        ),
        migrations.AlterField(
            model_name='tginfo',
            name='tg_sc_r',
            field=models.IntegerField(null=True, verbose_name='推广首充人数'),
        ),
        migrations.AlterField(
            model_name='tginfo',
            name='tg_sm_r',
            field=models.IntegerField(null=True, verbose_name='推广实名人数'),
        ),
        migrations.AlterField(
            model_name='tginfo',
            name='tg_xztz_j',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='推广新增金额'),
        ),
        migrations.AlterField(
            model_name='tginfo',
            name='tg_xztz_r',
            field=models.IntegerField(null=True, verbose_name='推广新增人数'),
        ),
        migrations.AlterField(
            model_name='tginfo',
            name='tg_zhu_r',
            field=models.IntegerField(null=True, verbose_name='推广注册人数'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='timeslot',
            field=models.IntegerField(null=True, verbose_name='时间段'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='tz_r',
            field=models.IntegerField(null=True, verbose_name='投资人数'),
        ),
    ]
