# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-18 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0053_auto_20171109_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseinfo',
            name='zg_j',
            field=models.DecimalField(decimal_places=2, max_digits=30, null=True, verbose_name='站岗金额'),
        ),
    ]
