# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-05 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0054_auto_20171218_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseinfo',
            name='cz_tz',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True, verbose_name='充值并投资'),
        ),
        migrations.AddField(
            model_name='baseinfo',
            name='xt_j',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True, verbose_name='续投金额'),
        ),
    ]
