# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-09 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0055_auto_20180105_1035'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReCasting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qdate', models.DateField(db_index=True, verbose_name='日期')),
                ('kefuname', models.CharField(max_length=64, null=True, verbose_name='客服姓名')),
                ('ft_r', models.IntegerField(null=True, verbose_name='首投后复投人数')),
                ('st_r', models.IntegerField(null=True, verbose_name='首投人数')),
                ('ft_lv', models.DecimalField(decimal_places=2, max_digits=20, null=True, verbose_name='复投率')),
                ('ft_j', models.DecimalField(decimal_places=2, max_digits=20, null=True, verbose_name='复投金额')),
                ('day_t_j', models.DecimalField(decimal_places=2, max_digits=20, null=True, verbose_name='当日投资金额')),
                ('month_t_j', models.DecimalField(decimal_places=2, max_digits=20, null=True, verbose_name='当月投资金额')),
            ],
            options={
                'verbose_name': '专属客服复投数据',
                'verbose_name_plural': '专属客服复投数据',
                'db_table': 'rzjf_re_casting',
            },
        ),
    ]
