# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-05 18:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0058_auto_20180305_1740'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='recasting',
            unique_together=set([('qdate', 'kefuname')]),
        ),
    ]
