# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-13 07:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='部门名称')),
            ],
            options={
                'verbose_name_plural': '部门表',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='菜单名称')),
                ('url_type', models.SmallIntegerField(choices=[(0, 'relative_name'), (1, 'absolute_url')], verbose_name='URL类型')),
                ('url_name', models.CharField(max_length=64, verbose_name='URL名称')),
            ],
            options={
                'verbose_name_plural': '菜单表',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='角色名称')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('menus', models.ManyToManyField(blank=True, to='dm.Menu', verbose_name='所属菜单')),
            ],
            options={
                'verbose_name_plural': '角色表',
            },
        ),
        migrations.CreateModel(
            name='SQLContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='sql内容')),
            ],
            options={
                'verbose_name_plural': 'SQL内容表',
            },
        ),
        migrations.CreateModel(
            name='SQLRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sql_name', models.CharField(max_length=64, verbose_name='SQL名称')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dm.Department', verbose_name='对应部门')),
                ('sql_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dm.SQLContent', verbose_name='对应SQL内容')),
            ],
            options={
                'verbose_name_plural': 'SQL记录表',
            },
        ),
        migrations.CreateModel(
            name='SQLTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='sql标签名称')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name_plural': 'SQL标签表',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=32, null=True, verbose_name='姓名')),
                ('roles', models.ManyToManyField(blank=True, to='dm.Role', verbose_name='所属角色')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '账户表',
            },
        ),
        migrations.AddField(
            model_name='sqltag',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dm.UserProfile', verbose_name='创建者'),
        ),
        migrations.AddField(
            model_name='sqlrecord',
            name='sql_tags',
            field=models.ManyToManyField(blank=True, to='dm.SQLTag', verbose_name='对应SQL标签'),
        ),
        migrations.AddField(
            model_name='sqlrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dm.UserProfile', verbose_name='创建者'),
        ),
    ]
