# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-13 08:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sqlrecord',
            name='sql_name',
            field=models.CharField(max_length=64, unique=True, verbose_name='SQL名称'),
        ),
    ]
