# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-07 15:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daily', '0002_auto_20180307_1527'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WDTY_Info',
            new_name='WDTYInfo',
        ),
        migrations.RenameModel(
            old_name='WDZJ_Info',
            new_name='WDZJInfo',
        ),
    ]
