# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-08 11:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daily', '0003_auto_20180307_1529'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='collectclassify',
            unique_together=set([('qdate', 'term', 'collect_type')]),
        ),
        migrations.AlterUniqueTogether(
            name='withdrawclassify',
            unique_together=set([('qdate', 'term', 'withdraw_type')]),
        ),
    ]
