CREATE TABLE `05b_0base` (
  `pk_id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `bid` int(11) unsigned NOT NULL ,
  `status` int(2) NOT NULL DEFAULT '0' COMMENT '状态:0 待初审,1 初审通过,2 初审失败,3 成交[满标复审通过] 4.复审失败,5 用户自行撤销 6  已结案 7 自动投标中 8 复审中[转账队列还没执行]',
  `curstate` int(2) NOT NULL DEFAULT '0' COMMENT '标的当前状态[等于冗余 base中的status 附加]3 表示已复审待还中,4 已还投资人，仍处于垫资垫付中,6 已结案 ',
  `stoptrans` int(11) NOT NULL DEFAULT '0',
  `diya_type` tinyint(1) NOT NULL DEFAULT '0' COMMENT '抵押类型，0 普通抵押，1 质押[车不开走]',
  `cid` int(11) NOT NULL DEFAULT '0' COMMENT '[冗余]借款人所属站点[注 这里既是冗余 同时也是记录当时的分站情况]',
  `uid` int(11) NOT NULL DEFAULT '0' COMMENT '用户名称',
  `aid` int(10) NOT NULL DEFAULT '0' COMMENT '标帐户id',
  `name` varchar(255) NOT NULL DEFAULT '' COMMENT '标题',
  `flag` tinyint(3) NOT NULL DEFAULT '0' COMMENT '属性:0 默认 ， 1 推荐标 ，2 快借标 ， 3 抵押标[ 有抵押物]， 4 秒表 5-体验标 6-债权标 7-急转标 8-流转标',
  `account` decimal(12,2) NOT NULL DEFAULT '0.00' COMMENT '借贷总金额',
  `account_diya` decimal(12,2) NOT NULL DEFAULT '0.00' COMMENT '合集支付的抵押金',
  `account_diyafanhuan` decimal(12,2) NOT NULL DEFAULT '-1.00' COMMENT '返还的抵押金[剩余的则被充公] [返还操作只能操作一次，如果返还这里大于-1 那么说明已经发还，不可再次返还了]',
  `account_zjf` decimal(12,2) NOT NULL DEFAULT '0.00' COMMENT '中介费',
  `bid_bzj` float(12,2) NOT NULL DEFAULT '-1.00' COMMENT '此标的冻结保证金比例，如果为-1表示使用系统设置',
  `borrow_style` int(10) NOT NULL DEFAULT '0' COMMENT '还款方式，0 按月分期，1 月还息到期还本，2 等额本息 ，3 月还息到期还本(湖) ，4 月先还息，到期还本;9/到期还本息',
  `borrow_period` int(10) NOT NULL DEFAULT '0' COMMENT '借款期限',
  `pflag` int(11) NOT NULL DEFAULT '0' COMMENT '周期类型 0 月 1天 2 季',
  `borrow_apr` decimal(11,2) NOT NULL DEFAULT '0.00' COMMENT '借款利率',
  `borrow_webapr` decimal(12,2) NOT NULL DEFAULT '0.00' COMMENT '相对网站的收益年化',
  `borrow_contents` text COMMENT '借款的详情',
  `borrow_valid_time` int(10) NOT NULL DEFAULT '3' COMMENT '借款有效时间',
  `borrower_apr` decimal(11,2) NOT NULL DEFAULT '0.00' COMMENT '借款人利率',
  `tender_account_min` int(11) NOT NULL DEFAULT '0' COMMENT '投资人最小的投资额',
  `tender_account_max` int(11) NOT NULL DEFAULT '0' COMMENT '投资人最大的投资额',
  `limit_money` varchar(50) NOT NULL DEFAULT '' COMMENT '体验标投标的限定的金额值',
  `repay_each_time` varchar(250) NOT NULL DEFAULT '' COMMENT '每次还款的时间',
  `cash_status` int(2) NOT NULL DEFAULT '0',
  `verify_userid` int(11) NOT NULL DEFAULT '0' COMMENT '审核人',
  `verify_remark` varchar(255) NOT NULL DEFAULT '',
  `reverify_userid` int(11) NOT NULL DEFAULT '0' COMMENT '审核人',
  `reverify_remark` varchar(255) NOT NULL DEFAULT '',
  `verify_username` varchar(30) NOT NULL DEFAULT '',
  `reverify_username` varchar(30) NOT NULL DEFAULT '',
  `days` int(10) NOT NULL DEFAULT '0' COMMENT '>0表示天标，否则算月标',
  `time_h` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `is_xudai` tinyint(1) NOT NULL DEFAULT '0' COMMENT '默认0 设置成1 表示是续贷标 2013-02-28开始有效',
  `repay_account` decimal(12,2) NOT NULL DEFAULT '0.00' COMMENT '应还总额 [=应还本金+应换利息]',
  `borrow_yongtu` varchar(200) DEFAULT NULL COMMENT '借款用途',
  `repay_account_capital` decimal(12,2) NOT NULL DEFAULT '0.00' COMMENT '应还本金',
  `repay_account_interest` decimal(12,2) NOT NULL DEFAULT '0.00' COMMENT '应还利息',
  `repay_account_other` decimal(12,2) NOT NULL DEFAULT '0.00' COMMENT '其他费用 管理费GPS费用 [注：包括中介费 不包括GPS押金]',
  `verify_time` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '初审',
  `reverify_time` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '复审时间',
  `borrow_jiangli` decimal(12,2) NOT NULL DEFAULT '0.00' COMMENT '奖励金额,单位元',
  `tend_jiangli_type` int(11) NOT NULL DEFAULT '0' COMMENT '奖励类型设置【值按位运算1、2、4、8、16....】;1=app投标',
  `app_jiangli` decimal(12,2) unsigned NOT NULL DEFAULT '0.00' COMMENT '手机投标奖励',
  `uid_add` int(11) NOT NULL DEFAULT '0' COMMENT '添加用户id',
  `uname_add` varchar(30) NOT NULL DEFAULT '' COMMENT '添加用户名字',
  `uid_zj` int(11) NOT NULL DEFAULT '0',
  `uname_zj` varchar(50) NOT NULL DEFAULT '',
  `money_zj` decimal(12,2) NOT NULL DEFAULT '0.00' COMMENT '已体现的中介费金额',
  `dj_type` int(11) NOT NULL DEFAULT '0' COMMENT '首期冻结类型，0 不冻结 1 冻结首期的还款额度（本息+手续费） , 2 冻结首期的本息',
  `dj_sq` decimal(12,2) NOT NULL DEFAULT '0.00' COMMENT '当前被冻结住的首期还款金额，对于到期还本的情况在倒数第二期会被自动解冻，对于按月分期，在倒数第一起自动解冻',
  `lxglf` decimal(12,3) NOT NULL DEFAULT '-1.000' COMMENT '标的利息管理费',
  `note` varchar(8000) NOT NULL DEFAULT '' COMMENT '表说明',
  `is_old` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否为老站数据',
  `imeis` varchar(150) NOT NULL DEFAULT '' COMMENT 'gps 设备号',
  `bnum` int(11) NOT NULL DEFAULT '0' COMMENT '此借款人的第几个标',
  `yewuyuan` varchar(50) NOT NULL DEFAULT '',
  `yewuid` int(11) NOT NULL DEFAULT '0',
  `classify` int(11) DEFAULT NULL,
  `bnumht` char(12) NOT NULL DEFAULT '',
  `isapp` tinyint(2) NOT NULL DEFAULT '0' COMMENT '是否app标:0不是，1是',
  `doflag` int(11) DEFAULT NULL COMMENT '标特别类型，1表示是红包标【审核后自动增加0.1%的奖励】',
  `workflow_step` tinyint(1) NOT NULL DEFAULT '0' COMMENT '工作流的步骤',
  `infonum` int(11) DEFAULT '0' COMMENT '展示的分类id号',
  `min_period` int(11) NOT NULL DEFAULT '0' COMMENT '最短借款期限，如果此值大于0 则表明在这个周期前，不能提前一次性还请',
  `useruid` int(11) NOT NULL DEFAULT '0' COMMENT '资金使用方,满标复审后的资金流向 使用方',
  `isAssign` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否允许利息转让；0=否；1=是',
  `border` int(11) DEFAULT '5' COMMENT '标排序用 值小靠前',
  `hetong_tpl_id` int(11) DEFAULT '0' COMMENT '合同模板id',
  `pre_track_warning` int(11) DEFAULT '0' COMMENT '贷前跟踪日志功能使用，有主站客服回复，则把该字段改成1，对应标那行显示红色，分站人员回复后显示蓝色，更改为2',
  `sent_ancun` tinyint(1) DEFAULT '0' COMMENT '判断是否已发送安存',
  `save_ancun` varchar(32) DEFAULT '' COMMENT '保全号',
  `border_web` int(11) DEFAULT '5' COMMENT '标pc排序用 值小靠前',
  `tender_account_d` decimal(12,2) NOT NULL DEFAULT '0.00' COMMENT '投标单位的限制',
  `repay_interest_plus` decimal(12,2) NOT NULL DEFAULT '0.00' COMMENT '加息券产生的利息',
  `thhtbh` varchar(30) NOT NULL DEFAULT '' COMMENT '相关的第三方合同号，比如债权转让的合同号',
  `esc_status` smallint(4) DEFAULT '0' COMMENT '0未上标 1上标 2废标 3成标 4出账 5还款完成 ',
  PRIMARY KEY (`pk_id`),
  KEY `user_ids` (`uid`,`status`),
  KEY `status_2` (`verify_time`,`status`),
  KEY `uid_add` (`uid_add`),
  KEY `status` (`status`,`reverify_time`,`bnum`),
  KEY `curstate` (`curstate`,`verify_time`),
  KEY `verify_time` (`verify_time`),
  KEY `idx_uid` (`uid`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC;


insert into 05b_0base(`bid`,`status`,`curstate`,`stoptrans`,`diya_type`,`cid`,`uid` ,`aid`,`name` ,`flag` ,`account`,`account_diya` ,`account_diyafanhuan`,`account_zjf`,`bid_bzj`,`borrow_style` ,
`borrow_period`,`pflag`,`borrow_apr`,`borrow_webapr`,`borrow_contents`,`borrow_valid_time`,`borrower_apr`,`tender_account_min` ,`tender_account_max`,`limit_money`,`repay_each_time`,`cash_status`,`verify_userid`,
`verify_remark`,`reverify_userid`,`reverify_remark` ,`verify_username`,`reverify_username`,`days`,`time_h`,`is_xudai`,`repay_account`,`borrow_yongtu`,`repay_account_capital`,`repay_account_interest`,`repay_account_other`,
`verify_time`,`reverify_time`,`borrow_jiangli`,`tend_jiangli_type`,`app_jiangli`,`uid_add`,`uname_add`,`uid_zj`,`uname_zj`,`money_zj`,`dj_type`,`dj_sq`,`lxglf`,`note`,`is_old`,`imeis`,`bnum` ,`yewuyuan` ,`yewuid`,
`classify`,`bnumht`,`isapp` ,`doflag`,`workflow_step` ,`infonum`,`min_period`,`useruid`,`isAssign` , `border`,`hetong_tpl_id`,`pre_track_warning`,`sent_ancun`,`save_ancun`, `border_web` ,`tender_account_d` ,
`repay_interest_plus`,`thhtbh`,`esc_status`
) select `bid`,`status`,`curstate`,`stoptrans`,`diya_type`,`cid`,`uid` ,`aid`,`name` ,`flag` ,`account`,`account_diya` ,`account_diyafanhuan`,`account_zjf`,`bid_bzj`,`borrow_style` ,
`borrow_period`,`pflag`,`borrow_apr`,`borrow_webapr`,`borrow_contents`,`borrow_valid_time`,`borrower_apr`,`tender_account_min` ,`tender_account_max`,`limit_money`,`repay_each_time`,`cash_status`,`verify_userid`,
`verify_remark`,`reverify_userid`,`reverify_remark` ,`verify_username`,`reverify_username`,`days`,`time_h`,`is_xudai`,`repay_account`,`borrow_yongtu`,`repay_account_capital`,`repay_account_interest`,`repay_account_other`,
`verify_time`,`reverify_time`,`borrow_jiangli`,`tend_jiangli_type`,`app_jiangli`,`uid_add`,`uname_add`,`uid_zj`,`uname_zj`,`money_zj`,`dj_type`,`dj_sq`,`lxglf`,`note`,`is_old`,`imeis`,`bnum` ,`yewuyuan` ,`yewuid`,
`classify`,`bnumht`,`isapp` ,`doflag`,`workflow_step` ,`infonum`,`min_period`,`useruid`,`isAssign` , `border`,`hetong_tpl_id`,`pre_track_warning`,`sent_ancun`,`save_ancun`, `border_web` ,`tender_account_d` ,
`repay_interest_plus`,`thhtbh`,`esc_status` from wd.05b_0base WHERE time_h <= DATE_FORMAT(DATE_SUB(curdate(),INTERVAL 1 DAY),"%Y-%m-%d 23:30:00");
